### ISSUE TITLE
Why use both withsqlite and filedict?

### ISSUE THREAD

**Issue by petterreinholdtsen** [NickDaly/Plinth#58]
What is the difference between the two python libraries withsqlite and filedict.  Both seem to be sqlite backed python dicts for persistent storage.  Perhaps only one of them should be used by plinth?  The filedict.py file is included in the plinth source, while withsqlite is maintained externally.

**Comment by SunilMohanAdapa** [comment]
Both withsqlite and filedict have been removed [upstream](https://github.com/freedombox/Plinth/).
