### ISSUE TITLE
Impossible to edit user information

### ISSUE THREAD

**Issue by petterreinholdtsen** [NickDaly/Plinth#69]
This issue is also reported as <URL: https://bugs.debian.org/741919 >.

When using the plinth first-page module to create the initial plinth
admin user, the user is named 'First user - please change', and to
change this one is expected to visit System->Users and Groups->Edit or
Delete User to change the users name.  But this do not work.  The list
of users show up, but when clicking on the first user, the browser visit
<URL: https://<my-freedombox>/plinth/sys/users/edit/?username=firstuser >
which do not allow me to edit anything, but only show the user list
again.

I expected some form like the one presented when creating new users,
where I can change the full name and email address of the initial user.

**Comment by SunilMohanAdapa** [comment]
This is now fixed [upstream](https://github.com/freedombox/Plinth/).

**Comment by petterreinholdtsen** [comment]
OK.
