### ISSUE TITLE
bug reports

### ISSUE THREAD

**Issue by brokenisuseless** [NickDaly/Plinth#88]
someone needs to make it clear where to report, as in the debian bug report or here. also the link provided by plinth itself sends you to james git, not here

**Comment by SunilMohanAdapa** [comment]
The [FreedomBox Wiki](https://wiki.debian.org/FreedomBox/Plinth) now clearly mentions https://github.com/freedombox/Plinth/ as upstream and the place for reporting bugs related to Plinth.
